apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-game
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-game
  template:
    metadata:
      labels:
        app: webapp-game
    spec:
      containers:
      - name: webapp-game
        image: <account_id>.dkr.ecr.<region>.amazonaws.com/webapp-game:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-game-service
  namespace: public
spec:
  selector:
    app: webapp-game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
